name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
        env:
          input_github_token: ${{ secrets.INPUT_GITHUB_TOKEN }}
          test: "helloworld"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
