name: learn-github-actions
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          tag: '1.0.2'
          message: 'this is test tag'
