name: learn-github-actions
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          commitmsg: ${{ github.event.head_commit.message }}

      - uses: ./
        with:
          tag: '1.0.2'
          message: ${{ env.commitmsg }}
